language:
    - c
    - cpp

compiler:
    - gcc

before_install:
    - export NIGHTLY_HASH=`git ls-remote git://github.com/Embroidermodder/Embroidermodder.git | grep refs/heads/master | cut -f 1`
    - sudo apt-get update -qq

install:
    - sudo apt-get install git
    - git config --global user.email \<\>
    - git config --global user.name "Embroidermodder-Travis"

before_script:
    - cat /etc/lsb-release
    - uname -a

script:
    # linux64
    - PLATFORM=linux64
    - cd ~
    - git clone https://Embroidermodder-Travis:${NIGHTLY_TOKEN}@github.com/Embroidermodder/travis-${PLATFORM}.git
    - cd travis-${PLATFORM}
    - git remote rm origin
    - git remote add origin https://Embroidermodder-Travis:${NIGHTLY_TOKEN}@github.com/Embroidermodder/travis-${PLATFORM}.git
    - git fetch origin
    - git checkout -b master origin/master
    - git commit --allow-empty -m "https://github.com/Embroidermodder/Embroidermodder/commit/${NIGHTLY_HASH}"
    - git push origin ${PLATFORM} &>/dev/null
    # osx64
    - PLATFORM=osx64
    - cd ~
    - git clone https://Embroidermodder-Travis:${NIGHTLY_TOKEN}@github.com/Embroidermodder/travis-${PLATFORM}.git
    - cd travis-${PLATFORM}
    - git remote rm origin
    - git remote add origin https://Embroidermodder-Travis:${NIGHTLY_TOKEN}@github.com/Embroidermodder/travis-${PLATFORM}.git
    - git fetch origin
    - git checkout -b master origin/master
    - git commit --allow-empty -m "https://github.com/Embroidermodder/Embroidermodder/commit/${NIGHTLY_HASH}"
    - git push origin ${PLATFORM} &>/dev/null


env:
  global:
    - secure: "X6MHmWJqMYh/wo/gstjYtpFf5A/nMNfjODscifQW9gqIEeFd+nrhjL6vtFwlsEAq36MnKijDDQT5tfCgE+yNKC0aT/AyDmKgpd3HMrgHi675mRIFZsXIQzHoIQx9/nHDgGrJPHHY1Jw1k/k43qJputcxBVJG3kpWoO8aieOOfuA="

notifications:
  recipients:
    - embroidermodder@gmail.com
  email:
    on_success: change
    on_failure: always
