language:
    - c
    - cpp

compiler:
    - gcc

before_install:
    - PLATFORM=linux64
    - export NIGHTLY_DATE=`date`
    - export NIGHTLY_BUILDNUM=`date +%Y%m%d%H%M%S`
    - export NIGHTLY_HASH=`git ls-remote git://github.com/Embroidermodder/Embroidermodder.git | grep refs/heads/master | cut -f 1`
    - sudo apt-get update -qq

install:
    - sudo apt-get install git qt4-qmake libqt4-opengl-dev kdelibs5-dev valgrind

before_script:
    - cat /etc/lsb-release
    - uname -a

script:
    - ROOT_BUILD_DIR=`pwd`
    - cd project-files/qmake
    - qmake
    - make
    - ./libembroidery-convert
    - which ../../embroidermodder2/embroidermodder2

after_success:
    - git config --global user.email \<\>
    - git config --global user.name "Embroidermodder-Travis"
    - cd ~
    - git clone https://Embroidermodder-Travis:${NIGHTLY_TOKEN}@github.com/Embroidermodder/nightly-ci.git
    - cd nightly-ci
    - git remote rm origin
    - git remote add origin https://Embroidermodder-Travis:${NIGHTLY_TOKEN}@github.com/Embroidermodder/nightly-ci.git
    - git fetch origin
    - git checkout -b $PLATFORM origin/$PLATFORM
    - README_FILE=README.md
    - rm -f $README_FILE
    - echo "Nightly Build" >> $README_FILE
    - echo "------------------------------" >> $README_FILE
    - echo "" >> $README_FILE
    - echo "Commit Date: $NIGHTLY_DATE" >> $README_FILE
    - echo "Commit Build Number: $NIGHTLY_BUILDNUM" >> $README_FILE
    - echo "Commit Hash: $NIGHTLY_HASH" >> $README_FILE
    - echo "" >> $README_FILE
    - echo "This is a development build for $PLATFORM and may be unstable or even unusable." >> $README_FILE
    - echo "USE AT YOUR OWN RISK AND HAVE FUN!" >> $README_FILE
    - echo "" >> README.md
    - ls
    - git commit -am "test build successful.\nBuildNumber $NIGHTLY_BUILDNUM\n Build Hash $NIGHTLY_HASH"
    - git push origin $PLATFORM

env:
  global:
    secure: JLGoPvDtTC/yLEIErTo2XJSnqwflVU+aVYkoIgHCQIqyt06a5MK3s7rpaTprjk+TWSLhrH5P2enUYjBRL2ivsG9Z2khH5zKg9m6RZu13I1PNBVmMRMcHLoaj+JjGYIeS7GvlkcWQYwS+o2j73/4wbdNNqDR6QDHVDEbDzD6vl/k=

notifications:
  recipients:
    - embroidermodder@gmail.com
  email:
    on_success: always # TODO: modify 'always' to 'change'
    on_failure: always

